#!/bin/sh

modprobe uio
insmod x86_64-wr-linuxapp-gcc/kmod/igb_uio.ko

echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
echo 1024 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages

mount -t hugetlbfs nodev /mnt/huge/
